name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */6 * * *'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo apt update && sudo apt install git curl python3-pip -y && pip3 install -U pip && pip3 install -U -r requirements.txt && python3 generator.py